### PR TITLE
DB-4060: Block Editor Alignment Options

### PR DESCRIPTION
**Pull request by enZane**
## What changes were made?
- Adds media queries to follow the actual implementation of the layout

## Where were the changes made?

- WP-Kit

## How have the changes been tested?
Locally, reviewed contrasting against Drupal

## Additional information

Don't forget to [add a changeset](https://github.com/pantheon-systems/decoupled-kit-js#generating-a-changeset) if needed!

### CODE REVIEW

**Review by CobyPear — APPROVED** [review]

**Comment by backlineint** [comment]
I'm not positive which PR this belongs on, but guessing this one :)

In this WordPress Post, the header section doesn't align the way I'd expect:

Screenshot at Nov 02 17-34-39

We probably didn't discuss this specifically, but I'd expect that to align with either the default (none), wide, or full widths. Comparing with WordPress, my guess is that this would align to wide.

Screenshot at Nov 02 17-35-56

The header presents a similar issue, but I'd say that is out of scope here.

**Comment by backlineint** [comment]
A little more subtle, but the header and the image aren't quite aligned.

Screenshot at Nov 02 17-37-09

The same problem looks to be happening in the Drupal starter as well.

Related to the previous comment, I'd expect the image to align to wide as well.

**Review by backlineint — CHANGES_REQUESTED** [review]
Added comments in the overview with screenshots.

**Review by CobyPear — COMMENTED** [review]
I am not seeing the widths applied to the Header block. Is there a reason this block is not included? 
Everything else seems G2G
image

**Comment by enZane** [comment]
> I am not seeing the widths applied to the Header block. Is there a reason this block is not included? Everything else seems G2G image

I saw it before and was because on the WP Block editor, that block has custom margins and that moves it, I guess we should honor custom settings like this

**Comment by enZane** [comment]
> I am not seeing the widths applied to the Header block. Is there a reason this block is not included? Everything else seems G2G image

I saw it before and was because on the WP Block editor, that block has custom margins and that moves it, I guess we should honor custom settings like this

**Comment by CobyPear** [comment]
@enZane I see it now, didn't notice the margin before.

**Pull request merged**
