### PR TITLE
DB-3650: Add image block support

### PR DESCRIPTION
**Pull request by enZane**
## What changes were made?
- Added styles to render image blocks

## Where were the changes made?
- WordPress-kit

## How have the changes been tested?
- Locally

## Additional information

Don't forget to [add a changeset](https://github.com/pantheon-systems/decoupled-kit-js#generating-a-changeset) if needed!

### CODE REVIEW

**Review by CobyPear — CHANGES_REQUESTED** [review]
Just one issue I'm seeing at the moment::
Looks like a right or left align images might have their container overlayed by another shown here

3 images on a page
Actual ⬆️

4 images on a page
Expected ⬆️

**Review by CobyPear — CHANGES_REQUESTED** [review]
LGTM. One tiny change, can you rename the `lib/tailwindCssPlugin` dir to `lib/tailwindcssPlugin` to keep the naming consistent (lowercase css)?

I like the idea of moving the components to their own files. Maybe we should do the same for Utilities, but it can be in another ticket or PR.

**Comment by enZane** [comment]
I also tried to move the utilities but I need to find a way to pass the theme function without TS problems, I'll give it another try in the gradient ticket

**Review by CobyPear — APPROVED** [review]
👍

**Pull request merged**
