### PR TITLE
Remove extra line

### PR DESCRIPTION
**Pull request by CdrMarks**
## What changes were made?
Removed extra line inside an example command

## Where were the changes made?
https://decoupledkit.pantheon.io/docs/decoupled-kit-overview

## How have the changes been tested?
Not tested.

## Additional information

Don't forget to [add a changeset](https://github.com/pantheon-systems/decoupled-kit-js#generating-a-changeset) if needed!
_I'm not sure if this is needed._

### CODE REVIEW

**Comment by CobyPear** [comment]
Hi @CdrMarks, thanks for the PR! This doc is generated from the [README.md in `packages/drupal-kit`](https://github.com/pantheon-systems/decoupled-kit-js/blob/canary/packages/drupal-kit/README.md). We have a ticket this sprint to regenerate our API reference which will pick up the newest version of this README. 

I'll keep this issue open in case you have any suggestions to that doc.

**Comment by CdrMarks** [comment]
Hi @CobyPear, the code example I was suggesting a change to was for `next-wordpress-starter`.  Does the [README.md in packages/drupal-kit](https://github.com/pantheon-systems/decoupled-kit-js/blob/canary/packages/drupal-kit/README.md) influence this example command?

**Comment by CobyPear** [comment]
> Hi @CobyPear, the code example I was suggesting a change to was for `next-wordpress-starter`. Does the [README.md in packages/drupal-kit](https://github.com/pantheon-systems/decoupled-kit-js/blob/canary/packages/drupal-kit/README.md) influence this example command?

Oh my apologies. I misread the file the change was in 😅
Disregard that. previous comment. I'll merge this in!

**Review by CobyPear — APPROVED** [review]

**Comment by CdrMarks** [comment]
Cool!  Should there be a changeset added to this PR?

**Comment by CobyPear** [comment]
> Cool! Should there be a changeset added to this PR?

No need for the docs site at this time

**Comment by CdrMarks** [comment]
Merge at will!

**Pull request merged**
